---
- debug: var=aws_access_key
- debug: var=aws_secret_key

- name: Create a new AWS EC2 instance
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    instance_tags:
      Name: "{{ aws_instance_name }}"
    count_tag:
      Name: "{{ aws_instance_name }}"
    instance_type: "{{ aws_instance_type }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 256
        delete_on_termination: true
    region: "{{ aws_region }}"
    group: "{{ aws_security_group }}"
    image: "{{ aws_image_AMI }}"
    assign_public_ip: yes
    vpc_subnet_id: "{{ aws_subnet_id }}"
    key_name: "{{ aws_public_key_name }}"
    wait: true
  register: ec2_result
  when:
    - aws_ec2_provision is defined
    - aws_ec2_provision == True


- debug: var=ec2_result